name: royal
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  go_router: 14.3.0
  dartz: 0.10.1
  get_it: 8.0.0
  dio: 5.7.0
  connectivity_plus: 6.0.5
  bloc_concurrency: 0.2.5
  envied: 0.5.4+1
  hive: 2.2.3
  hive_flutter: 1.1.0
  carousel_slider: 5.0.0
  firebase_core:
  firebase_auth:
  google_sign_in:
  flutter_staggered_grid_view:
  glass:
  clay_containers:

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  json_annotation:
  freezed_annotation:
  build_runner: 2.4.11
  json_serializable: ^6.5.0
  freezed: ^2.3.0
  envied_generator: ^0.5.4+1


flutter:
  uses-material-design: true
  generate: true
