// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATvHNButpCOxJrPLpiUaUZka-Tke_K3hM',
    appId: '1:344174708544:web:6d7021bb7b4ac671389ca5',
    messagingSenderId: '344174708544',
    projectId: 'royal-2a653',
    authDomain: 'royal-2a653.firebaseapp.com',
    storageBucket: 'royal-2a653.appspot.com',
    measurementId: 'G-7TXTKV12LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFvjHOdidj3Owl80jBlUP1flx-OBFn8AQ',
    appId: '1:344174708544:android:e3230c754aa0eb43389ca5',
    messagingSenderId: '344174708544',
    projectId: 'royal-2a653',
    storageBucket: 'royal-2a653.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzB8UyJv9jmoZkxQnSlQYCgn-7ORHZpWs',
    appId: '1:344174708544:ios:c0ecb8ab5c2c760f389ca5',
    messagingSenderId: '344174708544',
    projectId: 'royal-2a653',
    storageBucket: 'royal-2a653.appspot.com',
    iosBundleId: 'com.example.verygoodcore.royal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzB8UyJv9jmoZkxQnSlQYCgn-7ORHZpWs',
    appId: '1:344174708544:ios:fd29c0d3709b5736389ca5',
    messagingSenderId: '344174708544',
    projectId: 'royal-2a653',
    storageBucket: 'royal-2a653.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATvHNButpCOxJrPLpiUaUZka-Tke_K3hM',
    appId: '1:344174708544:web:38f412d916522c26389ca5',
    messagingSenderId: '344174708544',
    projectId: 'royal-2a653',
    authDomain: 'royal-2a653.firebaseapp.com',
    storageBucket: 'royal-2a653.appspot.com',
    measurementId: 'G-S7ZHJCF0EV',
  );
}
